# Generated by Django 5.1.2 on 2024-10-14 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_review_product_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='model_number',
            new_name='seller',
        ),
    ]
