# Generated by Django 5.1.2 on 2024-10-19 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_room_roommessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommessage',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.room'),
        ),
    ]
